apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-deployment
  labels:
    app: sba-kubernetes-cluster
spec:
  selector:
    matchLabels:
      app: sba-kubernetes-cluster
  replicas: 3
  template:
    metadata:
      labels:
        app: sba-kubernetes-cluster
    spec:
      containers:
      - name: sba-kubernetes-cluster
        image: danyyanez/sba_kuber
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sba-service
spec:
  type: NodePort
  selector:
    app: sba-kubernetes-cluster
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
