# github@simulationpoint
# Jesh Amera 01/18/2021
# sba.kubernetes-cluster

apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: jesh-kubernetes-app-deployment
spec:
  selector:
    matchLabels:
      app: kubernetesapp
  replicas: 3 
  template:
    metadata:
      labels:
        app: kubernetesapp
    spec:
      containers:
      - name: kubernetesapp
        image: 211896/jesh_docker_image
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: jesh-kubernetes-app-service
spec:
  type: NodePort
  selector:
    app: kubernetesapp
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31896
# part of this script is inspired by the template found https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/
